Delete spaces
feltcoop/felt-server pull request #182
Opened 2021-12-03 19:47 UTC by greatbacon

This PR adds server side logic for deleting a space as well as a first pass at front end UI & state management.

Still a bit of a WIP, I have one particular issue I need help with, which I will call out in line.

2021-12-03 19:49 UTC, greatbacon commented on src/lib/ui/ui.ts
> +			select_space({community_id: community_id, space_id: get(community).spaces[0]});
So (I think) I've got the logic sorted out for removing a deleted space from the community & space stores. I also want to update the selected space so that the UI doesn't hang on a deleted space & instead moves to a still extant space. I'm trying that there with the `select_space` line, but I guess I can't access that from within a sibling call? Any thoughts here @ryanatkn ?

2021-12-04 21:54 UTC, ryanatkn commented on src/lib/ui/SpaceDelete.svelte
> +	export let selectedSpace: Readable<Space>;
Small suggestion, I think this should be named `space` instead of `selectedSpace`.

2021-12-04 22:04 UTC, ryanatkn commented on src/lib/ui/ui.ts
> +			select_space({community_id: community_id, space_id: get(community).spaces[0]});
The `ui` local var can be used to reach the sibling methods, so `ui.select_space`. I think the right logic is to loop through each of `selectedSpaceIdByCommunity` and call `ui.select_space` for any of the `space_id`s matching the one in the params. The loop is needed because spaces do not belong to a single community.

2021-12-04 22:05 UTC, ryanatkn commented on src/lib/ui/ui.ts
> +				spaces: $community.spaces.filter((space) => space.space_id != space_id),
Minor nitpick - we probably should add `eslint` soon to get these kinds of things automatically as we're coding -- there's 4 instances of using `!=` in the PR instead of `!==`.

2021-12-04 22:27 UTC, ryanatkn commented on src/lib/ui/SpaceDelete.svelte
> +		errorMessage = '';
I think it'd be a fun refactor together to improve this code and make it more reusable, when we have an appetite for improving some UI patterns. Just off the top of my head:

- extract a generic component for the modal trigger, making the delete space form usable in other layouts
- use the `PendingButton` 
- standardize form behavior
  - async state (to do pending button automatically)
  -  error messages
  - using `Enter` to proceed generically through a form

2021-12-04 22:35 UTC, ryanatkn commented on src/lib/ui/SpaceDelete.svelte
> +			<h1>Delete {$selectedSpace.name} space?</h1>
This might be a good candidate for mounting a generic component like `SpaceInfo` -- it's not very useful yet but I think it'll be good to use it in situations like these to generate ideas. The `h1` could maybe then be generic and slightly clearer, "Delete this space?", but feel free to ignore this comment.

2021-12-04 22:36 UTC, ryanatkn commented on src/lib/vocab/space/spaceRepo.ts
> +				reason: `There was an issue deleting community_space: ${space_id}`,
copypaste typo, `deleting community_space` should be `deleting space`

2021-12-04 23:08 UTC, ryanatkn approved these changes

2021-12-04 23:11 UTC, ryanatkn commented on src/lib/vocab/space/spaceRepo.ts
> +		if (data_cs.count != 1) {
To support multiples i think this should be:
```suggestion
		if (data_cs.count === 0) {
```

2021-12-05 01:28 UTC, ryanatkn commented on src/lib/vocab/space/spaceRepo.ts
> +		const data = await db.sql<any[]>`
To handle spaces across communities, I think the delete space SQL should be executed only if there's 0 `community_spaces` remaining for this space.

Side note: we'll see more of this kind of complexity going forward because we handle spaces and communities as M:N. Like everything else it's open for reconsideration, but the benefits appear substantial for exploring cross-community governance.

2021-12-05 03:20 UTC, ryanatkn commented
This may be something to change in a followup PR:

There's a minor inconsistency where the `params` for `delete_space` include `community_id` and `space_id`, but `community_id` is not used on the server. Essentially that means it's a hard delete; in the repo method everything for the space is deleted, so if you're invited to collaborate on a document, and when you "delete" it from your workspace it deletes the original for the other person, which is probably a bad surprise unless it's adorned with red warning text.

I think a "soft" or "scoped" delete is a better default; "delete" should probably be more like "leave". We could provide the hard "delete" as a separate event with its own permissions.

In a soft delete, I think the logic should be to delete the `space` only when the `community_space` count is 0.

2021-12-05 03:52 UTC, ryanatkn commented
Fixed tests here: https://github.com/feltcoop/felt-server/pull/183

2021-12-05 04:04 UTC, ryanatkn requested changes
I had [one small PR](https://github.com/feltcoop/felt-server/pull/183) to fix tests, and one main change proposal, and the rest is minor and/or doesn't need immediate attention.

The proposed change: I think it'd be better to not return the `space_id` in the response data. The `200` should be enough I think? I also left a related comment about "hard" vs "soft" deletes (aka global or community-scoped) -- the `response` may be different for each of those, but I don't think either needs a `space_id` on it. Specifically I think the `delete_space` response schema should be `type: 'null'`.

2021-12-06 17:59 UTC, greatbacon commented on src/lib/ui/ui.ts
> +			select_space({community_id: community_id, space_id: get(community).spaces[0]});
Okay yeah, I agree with doing more event dispatching. I think opting for event design and response that allows for idempotent or NOP execution of events over adding an additional layer for tracking calling events seems like a more prudent long term solution. Thanks!

2021-12-06 18:05 UTC, greatbacon commented on src/lib/vocab/space/spaceRepo.ts
> +		if (data_cs.count != 1) {
This can only delete 1 space at a time though? The input param is a single number, not an array.

2021-12-06 18:07 UTC, greatbacon commented on src/lib/ui/SpaceDelete.svelte
> +			<h1>Delete {$selectedSpace.name} space?</h1>
I think I'll save any UI convos for a future refactor (per above comment).

2021-12-06 18:14 UTC, greatbacon commented
> I had [one small PR](https://github.com/feltcoop/felt-server/pull/183) to fix tests, and one main change proposal, and the rest is minor and/or doesn't need immediate attention.
> 
> The proposed change: I think it'd be better to not return the `space_id` in the response data. The `200` should be enough I think? I also left a related comment about "hard" vs "soft" deletes (aka global or community-scoped) -- the `response` may be different for each of those, but I don't think either needs a `space_id` on it. Specifically I think the `delete_space` response schema should be `type: 'null'`. I could see hard deletes possibly returning the count of community ids that were deleted, but returning a list of the community ids might be leaking sensitive info.

Yeah, that makes sense. I started at the DB layer and worked my way up. Figured returning the id of the deleted object would be useful for UI stuff but it's already passed as the param at the top. I'll clear that out.

Re: "hard" & "soft" deletes. I think keeping this as the admin/owner "hard" delete works for the short term, and I'll add an issue to implement a "soft" leave option which can include the cleanup logic to delete the space if no one is actually in it anymore.

2021-12-07 01:28 UTC, ryanatkn approved these changes

2021-12-07 01:50 UTC, ryanatkn commented on src/lib/vocab/space/space.events.ts
> +	},
```suggestion
	response: {
		$id: 'https://felt.social/vocab/delete_space_response.json',
		type: 'null',
	},
```

I think this is right, and then run `gro gen`.

2021-12-07 06:24 UTC, ryanatkn commented on src/lib/ui/ui.ts
> +			dispatch('select_space', {
This should be wrapped in an `if` that checks if the deleted `space_id` matches the selected one for each community of `selectedSpaceIdByCommunity`.

2021-12-07 06:27 UTC, ryanatkn commented
Sounds like a plan, one change then is to remove `community_id` from the params. I think the only reason to include it would be for authorization purposes but that's a future concern and would only be an optimization, if used at all.

2021-12-07 06:28 UTC, ryanatkn commented on src/lib/ui/ui.ts
> +				spaces: $community.spaces.filter((space) => space.space_id !== space_id),
This logic needs to run for each community, not just the given one.

2021-12-07 06:29 UTC, ryanatkn requested changes
Sounds like a plan, one change then to finish the hard delete functionality is to remove community_id from the params. I think the only reason to include it would be for authorization purposes but that's a future concern and would only be an optimization, if used at all.

2021-12-07 06:40 UTC, ryanatkn commented on src/lib/vocab/space/spaceRepo.ts
> +		if (data_cs.count != 1) {
It's the `community_spaces` table, so it'll error if more than one community has the space.

2021-12-07 19:02 UTC, ryanatkn approved these changes

2021-12-07 19:47 UTC, merged