Add githash to UI
feltcoop/felt-server pull request #184
Opened 2021-12-06 22:08 UTC by greatbacon

So this is a utility PR that attempts to add the trimmed (i.e. 7 char long) git hash to a spot in our UI for debugging & deployment confirmations.

It's still kind of a work in progress but I think I have an ok mechanism in place using the .env files & stuff.

However, I've got an issue now where when the deployment task runs to modify the .env.production file, the deployment artififact has already been built with whatever the previous value is.

Is there a way to instead wrap the build task with this git value change or something instead of putting it in the deployment task?

2021-12-06 23:51 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		await invokeTask('clean', {_: ['--sveltekit']});
The `build` task on the line below runs the clean task by default, so this shouldn't be needed. As a side note, the syntax is off here, calling `invokeTask` doesn't parse any args, so instead of this:

```ts
await invokeTask('clean', {_: ['--sveltekit']});
```

should be:

```ts
await invokeTask('clean', {_: [], sveltekit: true});
```

The `_: []` is unfortunate, and I think I'll make it optional in Gro.


or if you want to forward args:


```ts
await invokeTask('clean', {...args, sveltekit: true});
```

2021-12-07 00:04 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		fs.readFile(ENV_PROD, 'utf8', function (err, data) {
This may be causing the issue where your build artifact uses the previous value. The `readFile` and `writeFile` APIs are asynchronous but the control flow in the task isn't `await`ing them.

To fix I'd recommend deleting the `fs` import and using the promise-enabled `fs` on the task context, and using `await` when appropriate. You'll be able to remove this callback nesting.

A slight downside is that the standard Gro `fs` is all asynchronous for portability reasons. So this line:

```ts
run: async ({invokeTask}) => {
		const branch = fs.readFileSync('.git/HEAD').toString().trim();
```

becomes:

```
run: async ({invokeTask, fs}) => {
		const branch = fs.readFileSync('.git/HEAD').toString().trim();
```

The `fs` provided by Gro has both promises and better semantics than the Node `fs`, and it keeps our code more portable. Here's the docs: https://github.com/jprichardson/node-fs-extra

2021-12-07 00:09 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +			.readFileSync('.git/' + branch.substring(5))
Does  `substring(5)` belong on the line that defines `branch`?

2021-12-07 00:10 UTC, ryanatkn commented on src/infra/.env.development.default
> +VITE_GIT_VERSION=development
Is there a better name for this?

Instead of "git version"

"build hash"?

"git build hash"?

"git build"?

2021-12-07 00:28 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		await spawn('scp', [`${ENV_PROD}`, `${deployLogin}:${currentDeploy}/.env.production`]);
```suggestion
		await spawn('scp', [ENV_PROD, `${deployLogin}:${currentDeploy}/${ENV_PROD}`]);
```

2021-12-07 00:34 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		const ENV_PROD = '.env.production';
Might want to move this to `$lib/server/ent.ts` and use it in the 2 spots there.

2021-12-07 01:03 UTC, ryanatkn requested changes
Cool idea, had some minor notes and I think I found the bug.

Related -- what about tracking and displaying the build time in the same way?

2021-12-07 17:14 UTC, greatbacon commented on src/infra/serverDeploy.task.ts
> +		const ENV_PROD = '.env.production';
I think creating a dependency on the server code for our deploy task has the possibility to create more headaches than this refactor would solve.

2021-12-07 17:33 UTC, greatbacon commented
@ryanatkn So I implemented the changes but the problem still seems to be persisting. I wonder if it has to do with the .env.production values already being loaded into memory through the lifecycle of the task. So the file is changed before the build, but the unchanged value have already been loaded into memory and are carried through?

2021-12-07 19:14 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		const ENV_PROD = '.env.production';
Didn't see this before, it already has a dependency above on the line `const {fromEnv} = await import('$lib/server/env');`, and I think constants like these are a good example of the benefit of writing tasks in the same language as our apps. If the module in question started any infrastructure like the actual server I agree it shouldn't be imported.

2021-12-07 19:23 UTC, ryanatkn commented
That makes sense, two possible fixes come to mind.

The less disruptive one is to add a line that sets the `VITE_GIT_HASH` on the `import.meta.env` (and `process.env`? not sure). That may not work depending on Vite internals.

Another would be to change the line `await invokeTask('build');` to `await spawn('npx', ['gro', 'build']);` (imported as `import {spawn} from '@feltcoop/felt/util/process.js';`)

2021-12-08 04:08 UTC, ryanatkn approved these changes
Looks great. Just in case you didn't see this comment, was thinking it's worth reusing the constant in this case: https://github.com/feltcoop/felt-server/pull/184/files#r764291127

2021-12-08 17:26 UTC, ryanatkn commented on src/infra/serverDeploy.task.ts
> +		process.env.VITE_GIT_HASH = gitVersion;
I think there's a cleaner fix -- can you try deleting this line and moving `const {fromEnv} = await import('$lib/server/env');` to its location? The idea is that if you write out to the production env file first, if there are no imports elsewhere, then importing `fromEnv` here should have the fresh values.

2021-12-09 08:52 UTC, ryanatkn commented on src/infra/felt-server.conf
> +  server_name undefined;
This is a problem right?

2021-12-09 15:59 UTC, greatbacon commented
> Looks great. Just in case you didn't see this comment, was thinking it's worth reusing the constant in this case: https://github.com/feltcoop/felt-server/pull/184/files#r764291127

I saw that, but I didn't really like the idea of making our tasks have a direct dependency on server code. It felt like breaking the separation of concerns.

2021-12-09 16:06 UTC, greatbacon commented on src/infra/serverDeploy.task.ts
> +		const ENV_PROD = '.env.production';
Yeah, but that import isn't really a long term solution right? It's just a hack that's in place while some underlying gro infrastructure is fixed isn't it? Or am I misremembering?

2021-12-09 17:05 UTC, merged