Session setting working on login/logout
feltcoop/felt-server pull request #21
Opened 2021-04-20 22:30 UTC by greatbacon

This moves the community data into the session for the front end.

This makes it work when logging in or out, but if you refresh the page the data disappears, and my node-fu is failing me in how to solve that.

I think it has to do with `getSession` stuff, but I'm not 100% sure on what's happening to come up with a solution.

2021-04-20 22:57 UTC, ryanatkn commented on src/session/loginMiddleware.ts
> +			return send(res, 500, {reason: 'problem loading client session'});
This differs from the above pattern of `{reason: clientSessionResult.reason}` but I also like seeing it side by side, because it's not a final pattern anyway. Begs the question: should our db layer be responsible for generating user-facing messages? Or is that responsibility something to put in the middleware aka API handler layer?

2021-04-20 23:11 UTC, ryanatkn commented on src/routes/index.svelte
> +	$: communities = $session?.communities;
Thanks to this change, we can change the below code:

`{#if account && !$session.guest}`

to

`{#if communities}`

2021-04-20 23:26 UTC, ryanatkn commented on src/db/Database.ts
>  				if (data.length) {
I think this probably shouldn't return an error if no communities are found. I think it should just return an empty array? That would solve what's currently an error for newly created users.

2021-04-20 23:30 UTC, ryanatkn commented on src/db/Database.ts
> +						reason: `No id present for account: ${account}`,
`${account}` -> `${account.name}`

2021-04-20 23:52 UTC, ryanatkn commented
re: data gone on refresh

In `ApiServer`, for our hacky context route we have:

```ts
			.get('/api/v1/context', (req, res) => {
				send(res, 200, toClientContext(req));
			})
```

The problem (or part of it) is that the account is loaded because it's part of the session, but the rest of the info isn't there.

`toClientContext` could be changed to be `async`, so `send(res, 200, await toClientContext(req));`, and then load the communities from the database. in there. Could be refactored too.

`ClientAccountContext` needs `communities: Community[];` to match `AccountSession`. We'll refactor/rename/etc when SvelteKit is more stable.

and then in `hooks.ts` the `getSession` function needs to return the context's communities.

2021-04-20 23:54 UTC, ryanatkn requested changes
I think this'll get us to a working state, or close.

2021-04-22 15:54 UTC, greatbacon commented on src/session/loginMiddleware.ts
> +			return send(res, 500, {reason: 'problem loading client session'});
To your last point: I think at least having a common interface for client messaging (like `ClientResponse` or something) would be a decent soft reminder to not put sensitive information there.

To the bigger point of how to handle our error messaging, I'm not really sure. A pattern Kotlin has that I generally like is that you have discrete errors at the level they happen which can be logged for system purposes, then there is a catchall at the top level that is responsible for turning the lower level system errors into more generic/user friendly errors to return to the caller. Not sure what that would look like in a Node system but food for thought.

I think we may just have a bigger convo around our error handling architecture.

2021-04-22 15:56 UTC, greatbacon commented on src/routes/index.svelte
> +	$: communities = $session?.communities;
I think guest == accountless is a good semantic pattern.

For the sidebar I'll adopt `{#if communities}` but in this case that's because I actually do want to hide the sidebar if there are zero communities, even if the user is logged in.

2021-04-22 19:19 UTC, ryanatkn commented on src/session/loginMiddleware.ts
> +			return send(res, 500, {reason: 'problem loading client session'});
Yeah that makes sense, it's basically what I'm thinking, it's some top-level middleware or response handler or wrapper that standardizes everything. We'll architect that around Polka (and JSON schema validation stuff) when the time comes.

2021-04-22 19:24 UTC, ryanatkn commented on src/communities/communityMiddleware.ts
> +			const code = findCommunitiesResult.type === 'missingAccountId' ? 400 : 500;
I think `missingAccountId` should be a 500, so this could be simplified. Because the account is something we attach via the session, the value ought to be secure, meaning our internal systems goofed somewhere.

2021-04-22 19:27 UTC, ryanatkn commented on src/db/Database.ts
>  				account: Account,
What do you think of changing this API to take the `accountId` instead of the `account`? You could remove the `missingAccountId` error. I'm not sure if future requirements will need more account information.

2021-04-23 19:08 UTC, greatbacon commented on src/communities/communityMiddleware.ts
> +			const code = findCommunitiesResult.type === 'missingAccountId' ? 400 : 500;
accountId comes from the session header I thought, so wouldn't it be a malformed request to the server? Hence the 400.

2021-04-23 19:08 UTC, greatbacon commented on src/db/Database.ts
>  				account: Account,
yeah good call, principals of least concern and all that 🙃

2021-04-23 20:55 UTC, ryanatkn commented on src/session/sessionAccountMiddleware.ts
> +			return send(res, 404, {reason: 'no session found'});
I think the purpose of this middleware is to look for the `req.session` and attach the account info if it's available. Its previous role - returning the error - really belongs in a different layer. When those layers e.g. need an account and don't have one available, they'll return a `401`: <https://httpstatusdogs.com/401-unauthorized>

2021-04-23 20:58 UTC, ryanatkn commented on src/session/sessionAccountMiddleware.ts
>  		console.log('[sessionAccountMiddleware]', req.session.name); // TODO logging
Because the purpose of this middleware is to either add the `req.accountSession` or clear the `req.session`, I think we should do a check for `req.accountSession` here - if it exists, let's throw an error for ourselves.

2021-04-23 20:59 UTC, ryanatkn commented on src/server/ApiServer.ts
> +	accountSession?: AccountSession;
good stuff

2021-04-26 18:05 UTC, greatbacon commented on src/session/sessionAccountMiddleware.ts
>  		console.log('[sessionAccountMiddleware]', req.session.name); // TODO logging
So I think this is the last blocking piece, but I'm not really sure I understand what you're asking for/describing here. Could you draft a more concrete example of what you have in mind?

2021-04-26 18:35 UTC, ryanatkn commented on src/session/sessionAccountMiddleware.ts
>  		console.log('[sessionAccountMiddleware]', req.session.name); // TODO logging
This is what I was thinking, does it make sense?

```ts
import send from '@polka/send-type';

import type {ApiServer, Middleware} from '../server/ApiServer.js';

export const toSessionAccountMiddleware = (server: ApiServer): Middleware => {
	return async (req, res, next) => {
		if (req.accountSession) {
			return send(res, 500, {reason: 'invalid server configuration'});
		}
```

2021-04-26 18:36 UTC, ryanatkn commented on src/session/sessionAccountMiddleware.ts
>  		console.log('[sessionAccountMiddleware]', req.session.name); // TODO logging
Incidentally, I think this change will make CI pass.

2021-04-26 20:16 UTC, merged