Add spaces to context
feltcoop/felt-server pull request #26
Opened 2021-05-04 22:17 UTC by greatbacon

This PR adds `spaces` as an attribute of a community, pushes it up with an account's context, and then renders it.

@ryanatkn I think I'm barking up the wrong tree as far as reactivity goes. I was trying to get the selected community back up into the workspace and down into the `SpacesNav` but it clearly isn't working.

All the front end architecture is WIP, so open to any suggestions or paths forward there.

2021-05-04 23:36 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +		$: communityFocus = communities[index];
The `$: ` labels don't work inside function bodies, only at the top-level of a `script` in components. I think you want to track a `let focusedCommunityIndex: number | null = null;` declaration, then `$: focusedCommunity = communities[focusedCommunityIndex];`, and then a `changeFocus` function could just assign `focusedCommunityIndex = index;`.

2021-05-04 23:47 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +		$: communityFocus = communities[index];
Was looking at the code below, you could just store the community directly:

```ts
let selectedCommunity: Community | null = null;
cost selectCommunity = (community: Community) => {
  selectedCommunity = community;
};
```

```svelte
{#each communities as community}
	<button type="button" on:click={() => selectCommunity(community)}>{community.name} </button>
{/each}
```

2021-05-05 00:14 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +		$: communityFocus = communities[index];
I wrote these before seeing the usage in `Workspace.svelte`. So what I think you want is to make `selectedCommunity` the source of truth that lives as `let selectedCommunity: Community | null = null;` in `Workspace.svelte`, and then `CommunityNav.svelte` takes a `selectCommunity` function as a prop.

2021-05-05 00:17 UTC, ryanatkn commented on src/routes/index.svelte
> +	body {
This isn't actually being applied is it, because it's scoped to the component and there's no `<body>` in here?

2021-05-05 00:32 UTC, ryanatkn commented on src/lib/Workspace.svelte
> +	$: console.log(`the current community spaces are ${communityFocus.spaces}`);
to recap the stuff above, the straightforward way to make this reactive is to pass a function like this to child components:

```ts
let selectedCommunity = communities[0];
cost selectCommunity = (community: Community) => {
  selectedCommunity = community;
};
```

2021-05-05 00:34 UTC, ryanatkn commented on src/routes/index.svelte
> +	<Workspace {communities} />
:+1:

2021-05-05 00:47 UTC, ryanatkn requested changes
I can't test atm, will try to diagnose when we talk. (I doubt it's anything in this PR)

2021-05-05 01:14 UTC, greatbacon commented on src/routes/index.svelte
> +	body {
yeah, this is leftover from something else, will be cleared up.

2021-05-05 01:25 UTC, greatbacon commented on src/lib/Workspace.svelte
> +	$: console.log(`the current community spaces are ${communityFocus.spaces}`);
I did a little searching, but I'm not really turning up a great example of how to pass a function as a prop? Any guides/pointers?

2021-05-05 02:35 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +	const changeFocus = (index: number) => selectCommunity(communities[index]);
To simplify I'd remove this and call `selectCommunity` directly inside the #each

2021-05-05 02:39 UTC, ryanatkn commented on src/lib/SpaceNav.svelte
> +	{#if spaces}
Since the type of `spaces` is non-nullable we don't want `{#if spaces}`, and it makes sense we'd only mount this component if `spaces` was an array.

If you wanted to handle the case where there's an empty array, there's actually an optional `{:else}` block:

```svelte
	{#each spaces as {url} (url)}
		<button type="button" on:click={() => submitName(url)}>{url} </button>
	{:else}
		(no spaces)
	{/each}
```

Though my guess is that's not very helpful in this example.

2021-05-05 02:41 UTC, greatbacon commented on src/lib/SpaceNav.svelte
> +	{#if spaces}
The browser was throwing this error if I tried to iterate over it

```
index.mjs?v=33425075:1650 Uncaught (in promise) Error: {#each} only iterates over array-like objects.
    at validate_each_argument (index.mjs?v=33425075:1650)
    at Object.update [as p] (SpaceNav.svelte:11)
    at update (index.mjs?v=33425075:764)
    at flush (index.mjs?v=33425075:732)
```
Maybe that's more indicative of a server side issue passing a null back for spaces instead of an empty array... 🤔

2021-05-05 02:44 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +	$: selectedCommunity = selectedCommunityIndex ?? communities[selectedCommunityIndex];
Sorry I think this was confused by my multiple comments. The two lines here should be removed since they're being passed in as props. My previous comments assumed they were local to the component.

2021-05-05 02:46 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +		<button type="button" on:click={() => selectCommunity(communities[i])}
`selectCommunity(communities[i])` can be `selectCommunity(community)`

2021-05-05 02:47 UTC, ryanatkn commented on src/lib/CommunityNav.svelte
> +	{#each communities as community, i}
With the change below this you don't need the index, so:

`{#each communities as community (community.community_id)}`

2021-05-05 02:49 UTC, ryanatkn commented on src/lib/Workspace.svelte
> +		$: selectedCommunity = community;
no need for the `$: ` here

2021-05-05 02:49 UTC, ryanatkn commented on src/lib/Workspace.svelte
> +	$: selectedCommunity = communities[0];
should be `let selectedCommunity = communities[0];`

2021-05-05 02:54 UTC, ryanatkn commented on src/lib/SpaceNav.svelte
> +	{#if spaces}
Yeah we'd want to fix that upstream I think, an empty array makes usage much cleaner. I think we want to set any `null` values to `[]`. If Postgres doesn't make that easy we can just hackily iterate over them and assign `[]`, and revisit it when appropriate.

2021-05-05 02:58 UTC, ryanatkn commented on src/db/Database.ts
> +      				select array_to_json(coalesce(array_agg(row_to_json(d)), '{}'))
Not sure at all about this, but should it be `'[]'` instead?

2021-05-05 03:01 UTC, greatbacon commented on src/db/Database.ts
> +      				select array_to_json(coalesce(array_agg(row_to_json(d)), '{}'))
That's what the documentation said to use & I confirmed it was returning an empty JSON array as expected. I think `{}` is the SQL notation for an empty set, which then gets picked up by the next `array_to_json`

2021-05-05 03:02 UTC, ryanatkn commented on src/db/Database.ts
> +      				select array_to_json(coalesce(array_agg(row_to_json(d)), '{}'))
Got it thanks for the explanation.

2021-05-05 16:28 UTC, greatbacon commented
@ryanatkn anything else you can see? Or are we g2g?

2021-05-05 17:33 UTC, ryanatkn approved these changes

2021-05-05 17:34 UTC, ryanatkn commented
gtg! it's coming allliiiiive

2021-05-05 20:03 UTC, merged