Upgrade sveltekit
feltcoop/felt-server pull request #41
Opened 2021-06-14 21:56 UTC by greatbacon

This PR updates sveltekit & the node-adaptor we use for building. It's currently still somewhat a work in progress.

Currently the big outstanding issue is using the `cookieSession` to actually populate the session object we return via the getSession hook.

2021-06-14 22:17 UTC, ryanatkn requested changes
Great start, I'll see if I can dig up some links for cookie stuff. I've seen some examples that entail replacing our current `cookie-session` middleware with a cookie library and a bit more code.

2021-06-14 22:17 UTC, ryanatkn commented on .gitignore
> +deploy.tar
The `/functions` line can be removed above, and `/.svelte` needs to be changed to `/.svelte-kit`. (I'm trying to find the "add suggestions" feature)

2021-06-14 22:17 UTC, ryanatkn commented on .svelte-kit/dev/components/layout.svelte
> +<slot></slot>
this and other files will disappear when the gitignore is changed above

2021-06-14 22:17 UTC, ryanatkn commented on package.json
>      "vite": "^2.1.5"
SvelteKit now iincludes Vite internally, so `npm uninstall vite`

2021-06-14 22:17 UTC, ryanatkn commented on src/hooks.ts
> -const fetchJson = async (url: string, options: http.RequestOptions): Promise<any> =>
let's pretend this never happened

2021-06-14 22:17 UTC, ryanatkn commented on package.json
> +    "utf-8-validate": "^5.0.2",
Did you install `utf-8-validate` and `bufferutil` to fix errors? I don't see the imports so that's my best guess. I had to do this with `locate-character` in Gro, but I think it was just a temporary problem with Svelte types that I was solving. (reminds me..I'll see if I can delete that soon)

2021-06-15 22:12 UTC, greatbacon commented on package.json
> +    "utf-8-validate": "^5.0.2",
Yeah, they're marked as optional dependencies of `ws` (i think...) and it was blocking shit from starting at run time.

2021-06-15 23:50 UTC, ryanatkn commented on package.json
> +    "utf-8-validate": "^5.0.2",
Gotcha ok, looks like `bufferutil` is a major performance increase to `ws`, so it's good, just weird that they're not optional!

2021-06-16 00:31 UTC, ryanatkn approved these changes
The gitignore change isn't retroactive to committed files, so I think you can delete the `.svelte-kit` directory, commit the changes, and then this PR should look good.

2021-06-16 03:42 UTC, greatbacon commented
> The gitignore change isn't retroactive to committed files, so I think you can delete the `.svelte-kit` directory, commit the changes, and then this PR should look good.

I couldn't remember so I left it alone, thanks for pointing that out lol!

2021-06-16 03:46 UTC, merged