Add role backend services down to DB
feltcoop/felt-server pull request #478
Opened 2022-09-19 22:35 UTC by greatbacon

This PR adds the initial set of logic for creating, reading, updating, & deleting Roles from the Service layer down to the DB (technically it also adds the relation table for personas too but that work is for a later PR)

2022-09-20 23:57 UTC, ryanatkn requested changes

2022-09-20 23:57 UTC, ryanatkn commented on src/lib/db/migrations/00029-create-roles.js
> +		title text,
Should be unique right? Probably via an index, not a unique constraint? That way checking collisions on create can be fast with a good error message.

Thinking the field should be lowercased, or possibly using the `LOWER()` trick we do with persona/account names.

Also what do you think of renaming this from `title` to `name`? We haven't used `title` anywhere yet, and we've been using `name` as the unique string identifier for objects. I think `title` makes more sense when we need a displayed value that differs from the name.

2022-09-20 23:57 UTC, ryanatkn commented on src/lib/vocab/role/roleEvents.ts
> +	name: 'CreateCommunityRole',
Looks like the `Community` prefix is unnecessary and used only in some places, should be a simple global replace to fix unless there's a reason for it?

2022-09-20 23:57 UTC, ryanatkn commented on src/lib/vocab/role/roleEvents.ts
> +			community_id: {type: 'number'},
The delete schema has `actor` but the other events are missing it.

2022-09-20 23:57 UTC, ryanatkn commented on src/lib/vocab/role/roleHelpers.ts
> +export const createCommunityRole = async (
Do we expect these helpers to be called from multiple places where it'd be inconvenient to call them as services? If not it'd be simpler to inline this logic in the services and include the status codes.

2022-09-21 00:01 UTC, ryanatkn commented on src/lib/vocab/role/RoleRepo.ts
> +		if (!result.count) return NOT_OK;
```suggestion
```

2022-09-22 20:40 UTC, greatbacon commented on src/lib/vocab/role/roleHelpers.ts
> +export const createCommunityRole = async (
I started doing this as a future proof mechanism, as calling services from other services feels clunky & I've been enjoying having the "core business" logic separate from the "service response" logic.

2022-09-22 20:49 UTC, ryanatkn commented on src/lib/vocab/role/roleHelpers.ts
> +export const createCommunityRole = async (
Agree on the clunkiness, it's nice to just pass `repos` and inherit the transaction without the `serviceRequest` construction, which is verbose and more error prone.

How about we add the `.server` infix, giving us one of:

- `$lib/vocab/role/roleHelpers.server.ts`
- `$lib/vocab/role/roleServiceHelpers.server.ts`

2022-09-22 21:24 UTC, greatbacon commented on src/lib/vocab/role/roleHelpers.ts
> +export const createCommunityRole = async (
Fair enough, I'll roll up the helper functions to the services then.

2022-09-22 22:20 UTC, ryanatkn approved these changes
# 💯 

got one benign fix on a response schema

2022-09-23 00:20 UTC, ryanatkn commented on src/lib/vocab/role/roleEvents.ts
> +		required: ['role'],
```suggestion
		required: ['actor', 'role'],
```

2022-09-23 00:20 UTC, ryanatkn commented on src/lib/vocab/role/roleEvents.ts
> +			actor: {type: 'number'},
```suggestion
```

2022-09-23 19:40 UTC, merged